server:
  port: 8080
spring:
  ## JPA ##
  jpa:
    hibernate:
      ddl-auto: none
  ## DATASOURCE ##
  datasource:
    url: jdbc:h2:~/data/video;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

video:
  server:
    api: http://localhost:9090


