server:
  port: 8080
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE


home:
  path: D:/MyHomeVideo
video:
  server:
    api: http://localhost:9090

upload:
  server:
    ip: http://192.168.35.239:9091


