spring:
  ## JPA ##
  jpa:
    hibernate:
      ddl-auto: update
  ## DATASOURCE ##
  datasource:
    url: jdbc:h2:~/data/video;AUTO_SERVER=true
    username: sa
    password:
    driver-class-name: org.h2.Driver
  ### Rabbit MQ ###
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

### FILE PATH ###
home:
  path: D:\\MyHomeVideo
ffmpeg:
  path: C:\\Users\\KIM\\Desktop\\ffmpeg-20191229-e20c6d9-win64-static\\ffmpeg-20191229-e20c6d9-win64-static\\bin
server:
  port: 8082

### MQ Topic ###
topic:
  encode: my_encoder

### IP ###
video:
  server:
    ip: http://localhost:9090