server:
  port: 9090

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

home:
  path: D:\\MyHomeVideo
ffmpeg:
  path: C:\\Users\\KIM\\Desktop\\ffmpeg-20191229-e20c6d9-win64-static\\ffmpeg-20191229-e20c6d9-win64-static\\bin
thumbnail:
  path: C:\\Users\\KIM\\Desktop\\HomePlayer\\front\\src\\main\\resources\\static\\img\\thumbnail
